language: go
go:
  - "1.11.x"

dist: xenial

os: linux
services: docker

on:
  branch: develop

script:
  - if [[ "$TRAVIS_PULL_REQUEST" == false ]]; then bash docker_build.sh; fi

deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: build-test
    condition: $TRAVIS_OS_NAME = linux && $TRAVIS_PULL_REQUEST = false
