language: go
go:
  - "1.11.x"
dist: xenial

os: linux

services:
  - docker

install:
  - go get -u github.com/FiloSottile/vendorcheck
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $GOPATH/bin v1.13.2

script:
  - if [[ "$TRAVIS_PULL_REQUEST" == false ]]; then bash docker_build.sh; fi

deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: build-test
    condition: $TRAVIS_OS_NAME = linux && $TRAVIS_PULL_REQUEST = false
